-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employer_verification
(
    id integer NOT NULL,
    email_verification character varying(6) NOT NULL,
    system_staff_verification boolean NOT NULL,
    verification_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    website_address character varying(100) NOT NULL,
    phone_number character varying(10) NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_position
(
    id integer NOT NULL,
    position_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seeker_verification
(
    id integer NOT NULL,
    email_verification character varying(6) NOT NULL,
    verification_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id_no character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_workers
(
    id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification
(
    id integer NOT NULL,
    verification_code character varying(6) NOT NULL,
    is_verified boolean NOT NULL,
    verification_date date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employer_verification
    ADD FOREIGN KEY (verification_id)
    REFERENCES public.verification (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seeker_verification
    ADD FOREIGN KEY (verification_id)
    REFERENCES public.verification (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_workers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.verification
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;

END;